name: Build and Push Docker Image

on:
  push:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  VERSION: 0.18.0
  RESTIC_REPO: https://github.com/restic/restic.git
  RESTIC_DIR: restic-src

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: |
            name=ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=v${{ env.VERSION }}
            type=semver,pattern={{major}}.{{minor}},value=v${{ env.VERSION }}
            type=semver,pattern={{major}},value=v${{ env.VERSION }}

      - name: Show generated tags and labels
        run: |
          echo "Tags:"
          echo "${{ steps.meta.outputs.tags }}"
          echo
          echo "Labels:"
          echo "${{ steps.meta.outputs.labels }}"

      - name: Clone restic
        run: git clone --depth 1 --branch=v${VERSION} $RESTIC_REPO $RESTIC_DIR
        
      - name: Copy Dockerfile to restic source
        run: cp Dockerfile $RESTIC_DIR/
         
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: ${{ env.RESTIC_DIR }}
          file: Dockerfile
          # platforms: linux/386,linux/amd64,linux/arm,linux/arm64
          pull: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
